### ISSUE TITLE
After changing set , closing the content editor and not reloading the table, it shows wrong result , maybe from state/?

### ISSUE THREAD

**Issue by cowboybeer** [atelier-saulx/ui#122]

**Comment by cowboybeer** [comment]
<img width="1225" alt="Screenshot 2023-08-02 at 15 43 27" src="https://github.com/atelier-saulx/ui/assets/9952297/6fbff1d0-6564-487a-9eb6-9e29a106a34c">

It get's stuck in the ctx.data --> Refreshing the page/table helps fix it.

**Comment by jimdebeer** [comment]
new table ignore
