### ISSUE TITLE
Make playground features in UI, want to be able to interact with props

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#144]

**Comment by jimdebeer** [comment]
Back at it 🗡️

**Comment by jimdebeer** [comment]
a lot better but most components need some love

**Comment by jimdebeer** [comment]
- [ ] add code tab
- [ ] fix all components that are not displaying prop correctly
- [ ] fix parsing of props 
- [ ] add all missing propt to components that do not exist
