### ISSUE TITLE
Component: Toast

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#201]
https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3314&mode=design&t=BFDK6fqoHi4bVHHX-1

**Comment by maartensaulx** [comment]
- [ ] When I click close button in playground the action button inside disappears (wrong)
- [ ] Still want to see the different variants (destructive, warning, positive, brand, etc.) Now it only shows 'strong' as an option

**Comment by cowboybeer** [comment]
For the neutral "Action" color -> button doesn't accept informative color ?
