### ISSUE TITLE
Component: Table

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#206]
https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3309&mode=design&t=BFDK6fqoHi4bVHHX-1

**Comment by maartensaulx** [comment]
- [ ] Make the sorting nicer (discussed with Bence)
- [ ] Add possibility to resize columns

**Comment by vassbence** [comment]
- [ ] style scrollbar
