### ISSUE TITLE
Editor expanding makes playground crash (e.g. Slider)

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#208]

**Comment by jimdebeer** [comment]
Cannot reproduce
<img width="690" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/de710e43-cb44-4779-84b5-f186206ec230">

Do you mean this broken state?

**Comment by maartensaulx** [comment]
No, I meant opening this:

<img width="678" alt="Screenshot 2023-09-11 at 17 26 45" src="https://github.com/atelier-saulx/ui/assets/67953561/db2c09a7-731a-4cae-b1bb-6c3d42445285">

But now it works... dunno why it happened, Kyle also noticed it
]

**Comment by jimdebeer** [comment]
i deployed but did nothing
