### ISSUE TITLE
Component: Sidebar Navigation

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#210]
https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3306&mode=design&t=BFDK6fqoHi4bVHHX-1

**Comment by maartensaulx** [comment]
- [ ] Remove the collapsable/expandable labels from the sidebar **navigation**
- [ ] Add the collapsed/minized state of the sidebar navigation (icons only)
- [ ] Add the sidebar **list** --> it's the nested content of the selected sidebar navigation item (most of the time). 
- [ ] Make it work in the playground that it behaves like an actual sidebar; when select 1 item, deselect the other, etc. Add some icons, make it nice.

**Comment by maartensaulx** [comment]
<img width="1825" alt="Screenshot 2023-09-11 at 15 17 51" src="https://github.com/atelier-saulx/ui/assets/67953561/2fd95779-92e1-411f-aa0d-d5fb7bdbe4eb">

Take a good look at the components in Figma, it kinda explains what we need

**Comment by cowboybeer** [comment]
[ ] multiple menus on a page, gives multiple responsive close open buttons

**Comment by cowboybeer** [comment]
[ ] multiple menus on a page, gives multiple responsive close open buttons
