### ISSUE TITLE
Component: SelectInput

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#212]
https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3304&mode=design&t=BFDK6fqoHi4bVHHX-1

**Comment by maartensaulx** [comment]
- [ ] Add possibility to remove selected input with clickable icon at the right:

<img width="1554" alt="Screenshot 2023-09-11 at 16 07 49" src="https://github.com/atelier-saulx/ui/assets/67953561/b1dea47a-9053-4e64-9a0b-114a12b0f9b8">

This also sets the field back to the default 'placeholder' (We don't show that placeholder in the dropdown, opposed to what select inputs most of the time do. It's weird I don't want it)

**Comment by maartensaulx** [comment]
<img width="912" alt="Screenshot 2023-09-11 at 16 09 00" src="https://github.com/atelier-saulx/ui/assets/67953561/a1671937-7342-4d58-9d3b-c394a21d639f">

- [ ] Add a version that is smaller (36px high)
- [ ] Add possibility to give select input a fixed width or to wrap it around text (counts for both sizes, ignore screenshot above to that regard)
- [ ]

**Comment by maartensaulx** [comment]
To emphasise; this is how the states work:


https://github.com/atelier-saulx/ui/assets/67953561/63286f36-22cb-4a39-8699-9f87c2c25d94

**Comment by jimdebeer** [comment]
- [ ] Add a deselect option , and allow for undefined on the component itself (not to the actual input element)

**Comment by jimdebeer** [comment]
<img width="1498" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/d6d07757-9e43-45ce-860d-f05c3d7a5ec0">

Needs scroll bar
