### ISSUE TITLE
Component: Modal

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#216]
- [ ] Confimation modal  (create game modal for example, remove modal, etc)

[****](https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3318&mode=design&t=BFDK6fqoHi4bVHHX-1)

**Comment by maartensaulx** [comment]
There's a bunch of variants that we need to add I think, it's in the Figma but not sure how much we need in the playground

**Comment by jimdebeer** [comment]
Make all the examples in the playground
