### ISSUE TITLE
Component: FileInput

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#219]
https://www.figma.com/file/Mt9QoOjhJAmZIgAXstBzOT/New-Components?type=design&node-id=209%3A3295&mode=design&t=BFDK6fqoHi4bVHHX-1

**Comment by maartensaulx** [comment]
- [ ] Add the CMS structure to it
- [ ] Some additional options in the ... menu --> duplicate and stuff.

**Comment by maartensaulx** [comment]
<img width="1426" alt="Screenshot 2023-09-11 at 17 05 05" src="https://github.com/atelier-saulx/ui/assets/67953561/1156fa70-61ac-4c29-803b-c5690a220f4d">

**Comment by jimdebeer** [comment]
<img width="335" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/433ced4d-b0f2-4408-9cf4-6dd4443ad5ae">

2 times in menu

**Comment by jimdebeer** [comment]
Needs a lot of work - different styling 

![image](https://github.com/atelier-saulx/ui/assets/5682524/0016aa4e-1326-4151-a7a2-ad129a76082f)

![image](https://github.com/atelier-saulx/ui/assets/5682524/ba30106e-8598-410a-a719-1a2fb84de87b)


Different design as well

want it to fit in like any other input

- [ ] WIDTH needs to be respected
- [ ] Dropdown same as the other overlays
- [ ] maxWidth

**Comment by cowboybeer** [comment]
[ ] - allowed file types
