### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by maartensaulx** [atelier-saulx/ui#222]
- [x] missing icon before/after possibility
- [x] missing sizes
- [x] missing bare button
- [x] missing icon button (square and other spacing compared to normal button)

**Comment by jimdebeer** [comment]
bare button is Xsmall now i think

**Comment by jimdebeer** [comment]
<img width="1153" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/fbecd499-ace3-430f-98f1-3e69edddfe9c">

**Comment by jimdebeer** [comment]
playground is a lot better now ;)

**Comment by jimdebeer** [comment]
<img width="1338" alt="image" src="https://github.com/atelier-saulx/ui/assets/5682524/8bff7ffd-f27d-4d41-8da0-cdae7b0487a3">

**Comment by jimdebeer** [comment]
- [ ] Non focussable button or at least not visible focus state
- [ ] Focus state needs the correct color
