### ISSUE TITLE
LineGraph does not render

### ISSUE THREAD

**Issue by fuubi** [atelier-saulx/ui#52]
If the y values are all the same, the graph does not render anything, see: 

```tsx  
<LineGraph  data={[{x: 1, y: 2}, {x: 2, y: 2}, {x: 3, y: 2}]} />
```

![grafik](https://user-images.githubusercontent.com/12157082/208669300-7a0c4983-c82a-4ebc-aee8-022ad3993078.png)

Expected behavior:  Render a line, i.e., in the middle.

**Comment by jimdebeer** [comment]
@nfrade still needs some love

**Comment by jimdebeer** [comment]
fixed in current version
