### ISSUE TITLE
Add content edit section for based

### ISSUE THREAD

**Issue by jimdebeer** [atelier-saulx/ui#83]
Want to see the data using the dashboard config - will do design for the code together

**Comment by cowboybeer** [comment]
{
  "id": "via298eeb3",
  "config": {
    "type": "content",
    "view": "table",
    "showInMenu": false,
    "function": {
      "name": "db",
      "type": "query",
      "payload": {
        "$id": "$vars.target",
        "id": true,
        "children": {
          "$list": true,
          "title": true,
          "id": true
        }
      },
      "props": {
        "data": "$data.children",
        "onClick": {
          "view": {
            "type": "content-modal",
            "function": {
              "payload": {
                "$id": "$item.id",
                "title": true,
                "id": true
              }
            },
            "props": {
              "data": "$data",
              "fields": [
                {
                  "name": "TITLE TIME",
                  "field": "$item.title",
                  "type": "string"
                },
                {
                  "name": "ID",
                  "field": "$item.id",
                  "type": "id"
                }
              ]
            }
          }
        },
        "fields": [
          {
            "name": "TITLE TIME",
            "field": "$item.title",
            "type": "string",
            "onClick": {
              "view": "viewID OR VIEW",
              "state": {
                "target": "$item.id"
              }
            }
          },
          {
            "name": "ID",
            "field": "$item.id",
            "type": "id"
          }
        ]
      }
    }
  },
  "createdAt": 1686128414144,
  "name": "Powerful view",
  "type": "view",
  "updatedAt": 1686128414144
}

**Comment by jimdebeer** [comment]
- [ ] make function parser
- [ ] make view (top level) parser
- [ ] make props parser
- [ ] folder name types contains TABLE, CONTENT_MODAL, CUSTOM

**Comment by jimdebeer** [comment]
- [ ] seperation between categories
- [ ] fix routing / overlay in query param
- [ ] hidden categroy - only ref to categories dont do what we made now
- [ ] TARGET / ROUTE as a paramter
